pizzeria/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('menu/', views.PizzaList.as_view(), name='menu'),
    path('book-table/', views.BookTable.as_view(), name='book_table'),
    path(
        'fill-table-form/',
        views.FillTableForm.as_view(),
        name='fill_table_form'
    ),
    path(
        'update-booking/<int:pk>/',
        views.UpdateBooking.as_view(),
        name='update_booking'
    ),
    path(
        'cancel-booking/<int:pk>/',
        views.CancelBooking.as_view(),
        name='cancel_booking'
    ),
    path('<slug:slug>/', views.PizzaDetails.as_view(), name='pizza_details'),
]

yamyam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('pizzeria.urls'), name='pizzeria_urls'),
    path('accounts/', include('allauth.urls')),
]

pizzeria/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from datetime import timedelta
from django.core.exceptions import ValidationError


class Pizza(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    price = models.IntegerField()
    featured_image = CloudinaryField('image', default='placeholder')
    ingredients = models.TextField()

    class Meta:
        ordering = ['price']

    def __str__(self):
        return self.name


AMOUNT_OF_PERSONS = ((1, "One"), (2, "Two"), (3, "Three"), (4, "Four"))
AMOUNT_OF_TABLES = (
    (1, "One"), (2, "Two"), (3, "Three"), (4, "Four"),
    (5, "Five"), (6, "Six"), (7, "Seven"), (8, "Eight"),
    (9, "Nine"), (10, "Ten"), (11, "Eleven"), (12, "Twelve"),
    (13, "Thirteen"), (14, "Fourteen"), (15, "Fifteen"), (16, "Sixteen"),
    (17, "Seventeen"), (18, "Eighteen"), (19, "Nineteen"), (20, "Twenty")
)


class Booking(models.Model):
    username = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)
    email = models.EmailField()
    number_of_persons = models.IntegerField(
        choices=AMOUNT_OF_PERSONS, default=1)
    table_number = models.IntegerField(choices=AMOUNT_OF_TABLES)
    datetime = models.DateTimeField()

    class Meta:
        ordering = ['datetime']

    def __str__(self):
        return self.username

pizzeria/forms.py
from django import forms
from .models import Booking
from datetime import datetime


class BookTableForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ('email', 'number_of_persons',
                  'table_number', 'datetime')
        widgets = {
            'datetime': forms.DateTimeInput(
                attrs={
                    'type': 'datetime-local',
                    'class': 'form-control',
                    'min': datetime.now().strftime('%Y-%m-%dT%H:%M'),
                }
            )
        }

pizzeria/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Pizza, Booking
from .forms import BookTableForm
from django.contrib import messages
from datetime import datetime, timedelta
from django import forms
from django.urls import reverse_lazy


class Home(generic.ListView):

    model = Pizza
    queryset = Pizza.objects.order_by('price')
    template_name = 'home.html'


class PizzaList(generic.ListView):

    model = Pizza
    queryset = Pizza.objects.order_by('price')
    template_name = 'menu.html'
    paginate_by = 12


class PizzaDetails(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Pizza.objects
        pizza = get_object_or_404(queryset, slug=slug)

        return render(
            request,
            'pizza_details.html',
            {
                'pizza': pizza,
            }
        )


class BookTable(LoginRequiredMixin, CreateView):

    def get(self, request, *args, **kwargs):

        has_booking = Booking.objects.filter(username=request.user.username)

        if has_booking:
            return render(
                request,
                'booking_submitted.html',
                {
                    'booking': has_booking,
                }
            )

        else:
            return render(
                request,
                'book_table.html',
                {
                    'booked': False,
                    'book_table_form': BookTableForm(),
                },
            )

    def post(self, request, *args, **kwargs):

        book_table_form = BookTableForm(data=request.POST)

        """
        This if statement is to check if the user have submitted a form
        within 59 minutes window of any other booked table by any user.
        If so, it will prevent the user from booking that table
        """
        if request.method == "POST":
            form = BookTableForm(request.POST)

            if form.is_valid():
                table_number = request.POST['table_number']
                datetime = form.cleaned_data['datetime']

                existing_bookings = Booking.objects.filter(
                    table_number=table_number,
                    datetime__range=(datetime - timedelta(minutes=59),
                                     datetime + timedelta(minutes=59))
                )

                if existing_bookings.exists():
                    messages.error(request, "Sorry, Table is already booked")
                    return render(
                        request,
                        'book_table.html',
                        {
                            'book_table_form': BookTableForm(),
                        }
                    )

        if book_table_form.is_valid():
            book_table_form.instance.username = request.user.username
            book_table = book_table_form.save(commit=False)
            book_table.save()
        else:
            book_table_form = BookTableForm()

        return render(
            request,
            'book_table.html',
            {
                'booked': True,
                'book_table_form': BookTableForm(),
            },
        )


class FillTableForm(CreateView):

    def get(self, request, *args, **kwargs):

        return render(
            request,
            'book_table.html',
            {
                'booked': False,
                'book_table_form': BookTableForm(),
            },
        )

    def post(self, request, *args, **kwargs):

        book_table_form = BookTableForm(data=request.POST)

        """
        This if statement is to check if the user have submitted a form
        within 59 minutes window of any other booked table by any user.
        If so, it will prevent the user from booking that table
        """
        if request.method == "POST":
            form = BookTableForm(request.POST)

            if form.is_valid():
                table_number = request.POST['table_number']
                datetime = form.cleaned_data['datetime']

                existing_bookings = Booking.objects.filter(
                    table_number=table_number,
                    datetime__range=(
                        datetime - timedelta(minutes=59),
                        datetime + timedelta(minutes=59)
                    )
                )

                if existing_bookings.exists():
                    messages.error(request, "Sorry, Table is already booked")
                    return render(
                        request,
                        'book_table.html',
                        {
                            'book_table_form': BookTableForm(),
                        }
                    )

        if book_table_form.is_valid():
            book_table_form.instance.username = request.user.username
            book_table = book_table_form.save(commit=False)
            book_table.save()
        else:
            book_table_form = BookTableForm()

        return render(
            request,
            'book_table.html',
            {
                'booked': True,
                'book_table_form': BookTableForm(),
            },
        )


class UpdateBooking(UpdateView):

    model = Booking
    form_class = BookTableForm
    template_name = 'update_booking.html'

    def form_valid(self, form):
        form.save()
        return redirect('book_table')


class CancelBooking(LoginRequiredMixin, DeleteView):

    model = Booking
    success_url = reverse_lazy('book_table')
    template_name = 'cancel_booking.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Yamyam Pizzeria">
    <meta name="keywords" content="yamyam, pizzeria, food, book a table">

    <!-- Bootstrap link  -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
    />

    <!-- Font link  -->
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    />

    <!-- To avoid favicon error -->
    <link rel="shortcut icon" href="#">

    <!-- css link  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>Yamyam-pizzera</title>
</head>
<body>

    <!-- Nav -->
    <nav class="navbar navbar-expand-lg sticky-top navbar-light" id="navbar">
        <div class="container-fluid">
            <a class="navbar-brand px-2 fw-bold me-4" href="{% url 'home' %}">YamYam</a>
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
                id="nav-button"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 fw-bold">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'menu' %}">Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book_table' %}">Book_a_table</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            {% load i18n %}
                            <form method="post" action="{% url 'account_logout' %}">
                                {% csrf_token %}
                                {% if redirect_field_value %}
                                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                                {% endif %}
                                <button onclick="signOutChecker()" class="nav-link" id="button-signout" type="submit">Sign_out</button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            {% if user.is_authenticated %}
                <a class="fw-bold navbar-brand nav-link" href="{% url 'book_table' %}" id="username">{{ user }}</a>
            {% endif %}
        </div>
    </nav>

    <!-- Popup messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer id="footer">
        <div class="container-fluid">
            <div class="container-sm shadow-lg p-3 mb-5 bg-body-tertiary rounded">
                <p class="display-6">
                    <span class="fw-bold">Location:</span> Streetgatan 111, Norrkoping
                </p>
                <p class="display-6">
                    <span class="fw-bold">Call us:</span> 011 222 333
                </p>
                <p class="display-6">
                    <span class="fw-bold">Email:</span> yamyam@gmail.com
                </p>
                <div class="row text-center mt-4">
                    <div class="col-3 display-6">
                        <a
                        href="https://www.facebook.com"
                        target="_blank"
                        rel="noopener"
                        aria-label="Visit our Facebook page (opens in a new tab)"
                        ><i class="fa-brands fa-facebook"></i
                        ></a>
                    </div>
                    <div class="col-3 display-6">
                        <a
                        href="https://www.twitter.com"
                        target="_blank"
                        rel="noopener"
                        aria-label="Visit our Twitter page (opens in a new tab)"
                        ><i class="fa-brands fa-square-twitter"></i
                        ></a>
                        </div>
                    <div class="col-3 display-6">
                        <a
                        href="https://www.youtube.com"
                        target="_blank"
                        rel="noopener"
                        aria-label="Visit our Youtube page (opens in a new tab)"
                        ><i class="fa-brands fa-youtube"></i
                        ></a>
                    </div>
                    <div class="col-3 display-6">
                        <a
                        href="https://www.instagram.com"
                        target="_blank"
                        rel="noopener"
                        aria-label="Visit our Instagram page (opens in a new tab)"
                        ><i class="fa-brands fa-instagram"></i
                        ></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap script  -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
    ></script>
    <!-- Javascript -->
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/book_table.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!-- Booking form -->
<div class="container" id="booking-form-container">
    <div class="row">
        <div class="col-md-8 col-xl-6 card my-4 offset-md-2 offset-xl-3 shadow-lg">
            <div class="card-body">
                <h2>Book a table:</h2>

                <form method="POST">
                    {{ book_table_form | crispy }}
                    {% csrf_token %}
                    <button onclick="submitChecker()" class="btn mt-3 orange-button hover-button" id="button-form" type="submit" name="submit">Submit</button>
                </form>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/booking_submitted.html
{% extends 'base.html' %}

{% block content %}

<!-- List of Bookings -->
<div class="container d-flex justify-content-center" id="book-another-table-container">
    <div class="row">
        <div class="mt-5">
            <p class="h4">Hi, You want to book another table? Click <a href="{% url 'fill_table_form' %}">here</a></p>
        </div>
    </div>
</div>
<div class="container" id="has-booking-container">
    <div class="row">
        {% for b in booking %}
            <div class="col-md-10 col-lg-8 card my-4 offset-md-1 offset-lg-2 shadow-lg">
                <div class="card-body">
                    <p>You have a booking in {{ b.datetime }}</p>
                    <p>You have booked a table for {{ b.number_of_persons }} persons</p>
                    <p>Your table number is {{ b.table_number }}</p>
                    <a class="btn me-3 orange-button hover-button" href="{% url 'update_booking' b.pk %}">Update</a>
                    <a class="btn orange-button hover-button" href="{% url 'cancel_booking' b.pk %}">Remove</a>
                    <p>------------------------------------</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/cancel_booking.html
{% extends "base.html" %}

{% block content %}

<!-- Cancel booking -->
<div class="container" id="cancel-booking-container">
    <div class="row">
        <div class="col-md-8 col-xl-6 card my-4 offset-md-2 offset-xl-3 shadow-lg">
            <div class="card-body">
                <h2>Confirm Deletion</h2>
                <p>Are you sure you want to delete this booking?</p>

                <form method="post">
                    {% csrf_token %}
                    <button class="btn me-3 orange-button hover-button" type="submit">Yes, Delete</button>
                    <a class="btn orange-button hover-button" href="{% url 'book_table' %}">Cancel</a>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}

<!-- Home -->
<h1 class="text-center my-5 display-1 fw-bold">Yam Yam Pizzeria</h1>
<div class="container-fluid" id="home-container">
    <div class="row">
        <img src="https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8fA%3D%3D&w=1000&q=80" alt="" class="px-0">
    </div>
    <div class="container my-5">
        <div class="row">
            <p class="display-5 fw-bold" id="home-paragraph">
                <span class="display-4 fw-bolder">
                    Welcome to Yam Yam Pizzeria,
                </span>
                the ultimate destination for pizza lovers! Located in the heart of
                the city. Step inside and be greeted by the aroma of freshly baked
                pizza crusts, rich tomato sauce, and a delectable array of toppings.
            </p>
        </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %} {% block content %}

<h1 class="text-center my-5 display-1 fw-bold">Yam Yam Pizzeria</h1>
<div class="container-fluid">
  <div class="row">
    <img src="../static/images/pizza.jpg" alt="" class="px-0" />
  </div>
  <div class="container my-5">
    <p class="display-5 fw-bold">
      <span class="display-4 fw-bolder">Welcome to Yam Yam Pizzeria,</span>
      the ultimate destination for pizza lovers! Located in the heart of the
      city. Step inside and be greeted by the aroma of freshly baked pizza
      crusts, rich tomato sauce, and a delectable array of toppings.
    </p>
  </div>
</div>

{% endblock %}

templates/menu.html
{% extends "base.html" %}

{% block content %}

<!-- Menu -->
<div class="text-center">
    <h1 class="mt-5 mb-4 display-3">Pizza Menu</h1>
    <h2>Deliciously Irresistible Pizzas: A Slice of Heaven!</h2>
</div>
<div class="container">
    <div class="row my-5">
        <!-- For loop to show a list of all the pizzas -->
        {% for pizza in pizza_list %}
            <div class="col-12 col-sm-8 col-lg-4 col-xl-3 offset-sm-2 offset-lg-0">
                <div class="card mb-4" id="pizza-card">
                    <div class="card-body text-center py-4">
                        <h3 class="mb-3">{{ pizza.name }}</h3>

                        {% if "placeholder" in pizza.featured_image.url %}
                            <img
                                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEQmk1DR0p1Wi1QMLed3bcooFDFKwxNG9uMHFhoxDfsIPtMXCJFHag-idBCm4G5BRcTFY&usqp=CAU"
                                alt=""
                                class="card-img"
                            />

                        {% else %}
                            <img src="{{ pizza.featured_image.url }}" alt="" class="card-img" />
                        {% endif %}

                        <p class="mt-4 fw-bold">{{ pizza.price }} SEK</p>
                        <a href="{% url 'pizza_details' pizza.slug %}" class="post-link">Pizza Ingredients</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

    <!-- Pagination -->
    {% if is_paginated %}
        <nav aria-label="Page navigation" id="page-nav">
            <ul class="pagination justify-content-center">

                {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
                    </li>
                {% endif %}

                {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">NEXT &raquo;</a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    {% endif %}

</div>

{% endblock %}

templates/pizza_details.html
{% extends "base.html" %}

{% block content %}

<!-- Pizza details -->
<div class="container">
    <div class="row my-5 align-items-center justify-content-center">
        <div class="col-md-10 col-lg-8 col-xxl-6">
            <div class="card mb-4" id="pizza-details-card">
                <div class="card-body text-center py-4">
                    <h3 class="mb-3">{{ pizza.name }}</h3>

                    <!-- 
                        This if statement is to show a standard image
                        in case there was no image in the database
                     -->
                    {% if "placeholder" in pizza.featured_image.url %}
                        <img
                        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEQmk1DR0p1Wi1QMLed3bcooFDFKwxNG9uMHFhoxDfsIPtMXCJFHag-idBCm4G5BRcTFY&usqp=CAU"
                        alt=""
                        class="card-img"
                        />

                    {% else %}
                        <img src="{{ pizza.featured_image.url }}" alt="" class="card-img" />
                    {% endif %}

                    <p class="mt-4 fw-bold">{{ pizza.ingredients | safe }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/update_booking.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!-- Update Booking form -->
<div class="container" id="update-booking-container">
    <div class="row">
        <div class="col-md-8 col-xl-6 card my-4 offset-md-2 offset-xl-3 shadow-lg">
            <div class="card-body">
                <h2>Update the table:</h2>

                <form method="POST">
                    {{ form | crispy }}
                    {% csrf_token %}

                    <button class="btn mt-3 orange-button hover-button" type="submit" name="submit">Update</button>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}